// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Configuration is the predicate function for configuration builders.
type Configuration func(*sql.Selector)

// File is the predicate function for file builders.
type File func(*sql.Selector)
