// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"gofi/ent/configuration"
	"gofi/ent/file"

	"github.com/facebookincubator/ent/dialect/sql/schema"
	"github.com/facebookincubator/ent/schema/field"
)

var (
	// ConfigurationsColumns holds the columns for the "configurations" table.
	ConfigurationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "version", Type: field.TypeString, Nullable: true},
		{Name: "app_path", Type: field.TypeString, Nullable: true},
		{Name: "def_storage_path", Type: field.TypeString, Nullable: true},
		{Name: "theme_style", Type: field.TypeString},
		{Name: "theme_color", Type: field.TypeString},
		{Name: "nav_mode", Type: field.TypeString},
		{Name: "database_file_path", Type: field.TypeString},
		{Name: "custom_storage_path", Type: field.TypeString, Default: configuration.DefaultCustomStoragePath},
		{Name: "log_directory_path", Type: field.TypeString},
		{Name: "initialized", Type: field.TypeBool, Default: configuration.DefaultInitialized},
		{Name: "created", Type: field.TypeTime},
		{Name: "updated", Type: field.TypeTime},
	}
	// ConfigurationsTable holds the schema information for the "configurations" table.
	ConfigurationsTable = &schema.Table{
		Name:        "configurations",
		Columns:     ConfigurationsColumns,
		PrimaryKey:  []*schema.Column{ConfigurationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// FilesColumns holds the columns for the "files" table.
	FilesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "is_directory", Type: field.TypeBool, Default: file.DefaultIsDirectory},
		{Name: "size", Type: field.TypeInt, Default: file.DefaultSize},
		{Name: "extension", Type: field.TypeString},
		{Name: "mime", Type: field.TypeString},
		{Name: "path", Type: field.TypeString},
		{Name: "last_modified", Type: field.TypeInt64, Default: file.DefaultLastModified},
		{Name: "content", Type: field.TypeString},
	}
	// FilesTable holds the schema information for the "files" table.
	FilesTable = &schema.Table{
		Name:        "files",
		Columns:     FilesColumns,
		PrimaryKey:  []*schema.Column{FilesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ConfigurationsTable,
		FilesTable,
	}
)

func init() {
}
