// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"gofi/ent/configuration"
	"gofi/ent/predicate"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// ConfigurationDelete is the builder for deleting a Configuration entity.
type ConfigurationDelete struct {
	config
	predicates []predicate.Configuration
}

// Where adds a new predicate to the delete builder.
func (cd *ConfigurationDelete) Where(ps ...predicate.Configuration) *ConfigurationDelete {
	cd.predicates = append(cd.predicates, ps...)
	return cd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (cd *ConfigurationDelete) Exec(ctx context.Context) (int, error) {
	return cd.sqlExec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (cd *ConfigurationDelete) ExecX(ctx context.Context) int {
	n, err := cd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (cd *ConfigurationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: configuration.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: configuration.FieldID,
			},
		},
	}
	if ps := cd.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, cd.driver, _spec)
}

// ConfigurationDeleteOne is the builder for deleting a single Configuration entity.
type ConfigurationDeleteOne struct {
	cd *ConfigurationDelete
}

// Exec executes the deletion query.
func (cdo *ConfigurationDeleteOne) Exec(ctx context.Context) error {
	n, err := cdo.cd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{configuration.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (cdo *ConfigurationDeleteOne) ExecX(ctx context.Context) {
	cdo.cd.ExecX(ctx)
}
