// Code generated by entc, DO NOT EDIT.

package file

import (
	"gofi/ent/schema"
)

const (
	// Label holds the string label denoting the file type in the database.
	Label = "file"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name vertex property in the database.
	FieldName = "name"
	// FieldIsDirectory holds the string denoting the isdirectory vertex property in the database.
	FieldIsDirectory = "is_directory"
	// FieldSize holds the string denoting the size vertex property in the database.
	FieldSize = "size"
	// FieldExtension holds the string denoting the extension vertex property in the database.
	FieldExtension = "extension"
	// FieldMime holds the string denoting the mime vertex property in the database.
	FieldMime = "mime"
	// FieldPath holds the string denoting the path vertex property in the database.
	FieldPath = "path"
	// FieldLastModified holds the string denoting the lastmodified vertex property in the database.
	FieldLastModified = "last_modified"
	// FieldContent holds the string denoting the content vertex property in the database.
	FieldContent = "content"

	// Table holds the table name of the file in the database.
	Table = "files"
)

// Columns holds all SQL columns for file fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldIsDirectory,
	FieldSize,
	FieldExtension,
	FieldMime,
	FieldPath,
	FieldLastModified,
	FieldContent,
}

var (
	fields = schema.File{}.Fields()

	// descName is the schema descriptor for name field.
	descName = fields[0].Descriptor()
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator = descName.Validators[0].(func(string) error)

	// descIsDirectory is the schema descriptor for isDirectory field.
	descIsDirectory = fields[1].Descriptor()
	// DefaultIsDirectory holds the default value on creation for the isDirectory field.
	DefaultIsDirectory = descIsDirectory.Default.(bool)

	// descSize is the schema descriptor for size field.
	descSize = fields[2].Descriptor()
	// DefaultSize holds the default value on creation for the size field.
	DefaultSize = descSize.Default.(int)

	// descExtension is the schema descriptor for extension field.
	descExtension = fields[3].Descriptor()
	// ExtensionValidator is a validator for the "extension" field. It is called by the builders before save.
	ExtensionValidator = descExtension.Validators[0].(func(string) error)

	// descMime is the schema descriptor for mime field.
	descMime = fields[4].Descriptor()
	// MimeValidator is a validator for the "mime" field. It is called by the builders before save.
	MimeValidator = descMime.Validators[0].(func(string) error)

	// descPath is the schema descriptor for path field.
	descPath = fields[5].Descriptor()
	// PathValidator is a validator for the "path" field. It is called by the builders before save.
	PathValidator = descPath.Validators[0].(func(string) error)

	// descLastModified is the schema descriptor for lastModified field.
	descLastModified = fields[6].Descriptor()
	// DefaultLastModified holds the default value on creation for the lastModified field.
	DefaultLastModified = descLastModified.Default.(int64)

	// descContent is the schema descriptor for content field.
	descContent = fields[7].Descriptor()
	// ContentValidator is a validator for the "content" field. It is called by the builders before save.
	ContentValidator = descContent.Validators[0].(func(string) error)
)
